# Based on
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - rubocop-minitest
  - standard

inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false

Minitest/MultipleAssertions:
  Enabled: false

Style/IfInsideElse:
  Enabled: false
