# Based on
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - rubocop-performance # needed for standardrb
  - rubocop-minitest
  - standard/cop/block_single_line_braces # needed for standardrb

inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: disable
  SuggestExtensions: false
