name: kata-template

type: ruby

up:
  - ruby: 3.1.0
  - bundler

commands:
  test:
    run: |
      if [[ $# -eq 0 ]]; then
        bundle exec rake test
      else
        bundle exec m "$@"
      fi
  lint: bundle exec rubocop
