source "https://rubygems.org"

gem "activesupport"
gem "andyw8-seeing_is_believing"
gem "m"
gem "minitest"
gem "minitest-reporters"
gem "mocha"
gem "pry-byebug"
gem "rake"
gem "rubocop-lsp"
gem "rubocop-minitest"
gem "solargraph"
gem "standard"
